steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'line-bot'
      - '--source'
      - '.'
      - '--region'
      - 'asia-east1'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
